Delete unnecessary Contractor service functions and replace uses
nortan-ninc/plataforma pull request #118
Opened 2022-03-29 00:02 UTC by WilamisAviz15

2022-03-29 21:16 UTC, augustoicaro requested changes
Dá uma olhada nos pontos que levantei

2022-03-29 21:16 UTC, augustoicaro commented on src/app/pages/invoices/invoice-item/invoice-item.component.html
> +                    )
No HTML sempre que possível vamos usar o `transformPipe` combinando as funções. A nível de desempenho é sempre melhor usar um pipe no html do que uma função.

2022-03-29 21:16 UTC, augustoicaro commented on src/app/pages/invoices/invoice-item/invoice-item.component.ts
>          : '';
Aqui não precisa o operador ternário, o `idToProperty` já faz isso internamente, se o cara for indefinido retorna string vazia.

2022-03-29 21:16 UTC, augustoicaro commented on src/app/pages/invoices/invoice-item/invoice-item.component.ts
>            : '';
Mesma coisa aqui

2022-03-29 21:16 UTC, augustoicaro commented on src/app/pages/invoices/pdf.service.ts
>            : '',
Mesma coisa aqui

2022-03-29 23:22 UTC, augustoicaro commented on src/app/pages/invoices/invoice-item/invoice-item.component.html
>                    : ''
mesm coisa aqui

2022-03-30 00:06 UTC, EduhFarias commented on src/app/pages/invoices/pdf.service.ts
> +      ),
Nesse trecho aqui nós temos uma propriedade do invoice que já nos dá o nome completo, é inválido checar ela antes de fazer a chamada da função?

2022-03-31 18:35 UTC, augustoicaro commented on src/app/pages/invoices/pdf.service.ts
> +      ),
Essa propriedade opcioal pode não estar prenchida dependendo do contexto

2022-03-31 18:36 UTC, augustoicaro approved these changes

2022-04-01 22:01 UTC, merged