Remove unnecessary functions from Team service
nortan-ninc/plataforma pull request #120
Opened 2022-03-29 01:02 UTC by EduhFarias

2022-03-29 21:18 UTC, augustoicaro approved these changes

2022-03-30 16:42 UTC, leo-holanda requested changes
Conferir o ponto no PdfService

2022-03-30 16:42 UTC, leo-holanda commented on src/app/pages/invoices/pdf.service.ts
> +    switch (this.utils.idToProperty(invoice.nortanTeam, this.teamService.idToTeam, 'abrev')) {
A parte de geração de PDFs aparentemente quebrou.

![erro](https://user-images.githubusercontent.com/26936076/160887179-32ad8fab-1435-4bde-afe6-4ca255587ab7.png)

Talvez o erro seja a ausência do .bind() na função idToTeam, mas não sei.

2022-03-30 16:42 UTC, leo-holanda commented on src/app/pages/invoices/pdf.service.ts
> +    switch (this.utils.idToProperty(invoice.nortanTeam, this.teamService.idToTeam, 'abrev')) {
Sei que a gente combinou que essa parte fica no Definition de Done, mas quando vi o código fiquei curioso pra saber se funcionaria ou não.

2022-03-30 22:48 UTC, leo-holanda approved these changes

2022-03-31 00:40 UTC, merged