Delete user service functions and replace uses
nortan-ninc/plataforma pull request #122
Opened 2022-03-29 23:56 UTC by Elygledson

2022-03-30 19:59 UTC, EduhFarias commented on src/app/shared/services/user.service.ts
> -
Adiciona uma quebra de linha aqui

2022-03-30 20:02 UTC, EduhFarias requested changes

2022-03-30 20:02 UTC, EduhFarias commented on src/app/shared/services/user.service.ts
>        user: user,
Olhando o arquivo do seu branch, você não removeu as funções de acesso como dito na história. As funções idToAlgumaCoisa que podem ser trocadas por idToProperty do servico Utils não foram removidas.

2022-03-31 18:41 UTC, augustoicaro requested changes
Reverte tudo e começa novamente, como o @EduhFarias falou não era para fazer isso, dá uma olhada nos outros PR para entender melhor a tarefa, ou tira a dúvida com alguém.

2022-04-01 12:54 UTC, EduhFarias approved these changes

2022-04-01 22:00 UTC, augustoicaro requested changes
Tu deixo passar o ajuste do `idToProperty` com o pipe em 2 pontos. Dá um olhada onde marquei

2022-04-01 22:00 UTC, augustoicaro commented on src/app/pages/contracts/contract-item/contract-item.component.html
> +                      "
Esse uso do `tranformPipe` com o `IdToProperty` está errado, repetir o que foi feito no uso anterior

2022-04-01 22:00 UTC, augustoicaro commented on src/app/pages/contracts/contract-item/contract-item.component.html
> +                      "
Mesma coisa aqui

2022-04-05 00:09 UTC, augustoicaro approved these changes

2022-04-05 00:10 UTC, merged