Management module
nortan-ninc/plataforma pull request #123
Opened 2022-03-30 18:48 UTC by leo-holanda

2022-03-31 16:57 UTC, leo-holanda commented on src/app/pages/contracts/contract-item/management-tab/management-tab.component.html
> +        [value]="getPercentualProgress()"
Não usei o transformPipe aqui porque o retorno dele tá sempre como string e esse bind e o retorno da função é número, aí vou abrir uma task pra tentar corrigir isso

2022-03-31 18:03 UTC, leo-holanda commented on src/app/pages/contracts/contract-item/management-tab/management-tab.component.ts
> +  ];
Eu não sei se eu deveria ter criado um ENUM pra isso ou deixado no array mesmo. Como não faz comparação eu deixei no array

2022-03-31 18:08 UTC, leo-holanda commented on src/app/pages/contracts/contract-item/management-tab/management-tab.component.ts
> +      return +((progress / total) * 100).toFixed(2);
Eu não usei a função de porcentagem do stringUtils aqui porque ela retorna string e o bind do componente da barra precisa de um número. Eu fiz o teste de colocar + antes do retorno dessa função de porcentagem mas no fim fica NaN. Aí fiquei na dúvida se criava uma função de porcentagem que retorna number lá no stringUtils ou deixava só no componente mesmo já que é algo pontual

2022-03-31 18:44 UTC, augustoicaro commented on src/app/pages/contracts/contract-item/management-tab/management-tab.component.html
> +        [value]="getPercentualProgress()"
Transforma isso numa tarefa

2022-03-31 18:51 UTC, augustoicaro commented on src/app/pages/contracts/contract-item/management-tab/management-tab.component.ts
> +      return +((progress / total) * 100).toFixed(2);
É aquela velha questão da string do valor monetário, tem que usar o `moneyToNumber`. Esse vale a pena ajeitar aqui

2022-03-31 23:33 UTC, leo-holanda commented on src/app/pages/contracts/contract-item/management-tab/management-tab.component.html
> +        [value]="getPercentualProgress()"
Criada agora

2022-03-31 23:33 UTC, leo-holanda commented on src/app/pages/contracts/contract-item/management-tab/management-tab.component.ts
> +      return +((progress / total) * 100).toFixed(2);
Ok

2022-04-01 00:22 UTC, augustoicaro requested changes

2022-04-01 00:22 UTC, augustoicaro commented on src/app/pages/contracts/contract-item/management-tab/management-tab.component.ts
> +  getTotalDays(): number | undefined {
tirar o get do nome da função

2022-04-01 00:22 UTC, augustoicaro commented on src/app/pages/contracts/contract-item/management-tab/management-tab.component.ts
> +  getRemainingDays(): number | undefined {
tirar o get do nome da função

2022-04-01 00:22 UTC, augustoicaro commented on src/app/pages/contracts/contract-item/management-tab/management-tab.component.ts
> +  getPercentualProgress(): number {
tirar o get do nome da função

2022-04-01 00:22 UTC, augustoicaro commented on src/app/pages/contracts/contract-item/management-tab/management-tab.component.ts
> +  getAvaliableResponsibles(): Observable<User[]> {
tirar o get do nome da função

2022-04-01 00:22 UTC, augustoicaro commented on src/app/pages/contracts/contract-item/management-tab/management-tab.component.ts
> +  getItemTotalDays(item: ContractChecklistItem): number | undefined {
tirar o get do nome da função

2022-04-01 00:22 UTC, augustoicaro commented on src/app/pages/contracts/contract-item/management-tab/management-tab.component.ts
> +  getItemRemainingDays(item: ContractChecklistItem): number | undefined {
tirar o get do nome da função

2022-04-01 00:22 UTC, augustoicaro commented on src/app/pages/contracts/contract-item/management-tab/management-tab.component.ts
> +  getPercentualItemProgress(item: ContractChecklistItem): number {
tirar o get do nome da função

2022-04-01 00:22 UTC, augustoicaro commented on src/app/pages/contracts/contract-item/management-tab/management-tab.component.ts
> +  getItemProgressStatus(item: ContractChecklistItem): string {
tirar o get do nome da função

2022-04-01 00:22 UTC, augustoicaro commented on src/app/pages/contracts/contract-item/management-tab/management-tab.component.ts
> +  getAvaliableResponsibles(): Observable<User[]> {
Ajustar nome da função

2022-04-01 00:22 UTC, augustoicaro commented on src/app/pages/contracts/contract-item/management-tab/management-tab.component.ts
> +  getAvaliableResponsibles(): Observable<User[]> {
Mover função para o serviço de contrato e fazer reuso também no dialogo

2022-04-01 00:22 UTC, augustoicaro commented on src/app/pages/contracts/contract-item/management-tab/management-tab.component.ts
> +      return +((completedActionsQtd / item.actionList.length) * 100).toFixed(2);
Usas função de porcentagem da stringUtils

2022-04-01 00:22 UTC, augustoicaro commented on src/app/shared/services/contract.service.ts
> +  getDeadline(contract: Contract): Date | undefined {
tirar o get do nome da função

2022-04-01 00:22 UTC, augustoicaro commented on src/app/shared/services/contract.service.ts
> +  private getLatestEndDate(contract: Contract): Date {
tirar o get do nome da função

2022-04-01 18:23 UTC, leo-holanda commented on backend/src/models/contract.ts
> +  responsible: Ref<User>;
Ok

2022-04-02 00:51 UTC, leo-holanda commented on backend/src/models/contract.ts
> +  checklist: ContractChecklistItem[] = [];
Colocando pra me lembrar de fazer a função do playground

2022-04-04 22:31 UTC, augustoicaro approved these changes

2022-04-04 22:44 UTC, WilamisAviz15 approved these changes

2022-04-04 22:45 UTC, merged