save comments on db
nortan-ninc/plataforma pull request #125
Opened 2022-04-06 00:34 UTC by WilamisAviz15

2022-04-06 23:15 UTC, augustoicaro requested changes
Dá uma olhada nos pontos que levantei

2022-04-06 23:15 UTC, augustoicaro commented on src/app/pages/contracts/contract-item/management-tab/management-tab.component.html
> +            <b>{{ utils.idToProperty(comment.author, userService.idToUser.bind(userService), 'fullName') }}</b>
Usar o `transformPipe` combinando com o que você já escreveu. Tem outros exemplos disso pelo código.

2022-04-06 23:15 UTC, augustoicaro commented on src/app/pages/contracts/contract-item/management-tab/management-tab.component.ts
> +  avaliableContracts: Observable<Contract[]> = of([]);
Remover essas linhas, erro de merge

2022-04-06 23:15 UTC, augustoicaro commented on src/app/pages/contracts/contract-item/management-tab/management-tab.component.ts
> +  responsibleSearch = '';
Remover essas linhas, erro de merge

2022-04-06 23:15 UTC, augustoicaro commented on backend/src/models/message.ts
> +  contractId: Ref<Contract>;
Trocar nome para `contract`, um `Ref<Contract>` também pode ser um objeto

2022-04-06 23:15 UTC, augustoicaro commented on src/app/pages/contracts/contract-item/management-tab/management-tab.component.ts
> +          .filter((mFiltered) => mFiltered.contractId === this.iContract._id)
Nesse caso deveriamos comparar os 2 ids levando em conta que `Filtered.contrctId` pode ser um objeto de contrato por ser um `Ref`

2022-04-06 23:15 UTC, augustoicaro commented on src/app/pages/contracts/contract-item/management-tab/management-tab.component.ts
> +          .map((message) => {
Trocar map por `forEach`. Não tem diferença prática, mas a nível de compreensão o `map` tem um retorno(que não usamos) e o `forEach` não retorna nada.

2022-04-06 23:15 UTC, augustoicaro commented on src/app/pages/contracts/contract-item/management-tab/management-tab.component.ts
> +    this.newComment.contractId = this.iContract._id;
Nesse caso pode passar o `this.iContract` já que o modelo é um `Ref`.

2022-04-06 23:15 UTC, augustoicaro commented on src/app/shared/services/message.service.spec.ts
> +                return v;
Usar o `reviveDates`

2022-04-07 23:01 UTC, Elygledson approved these changes

2022-04-07 23:18 UTC, augustoicaro reviewed
Você esqueceu esse ponto?

2022-04-07 23:18 UTC, augustoicaro commented on src/app/pages/contracts/contract-item/management-tab/management-tab.component.ts
> +          .map((message) => {
Vi que você resolveu aqui, mas não fez a troca pelo `forEach`, era isso mesmo que você queria fazer?

2022-04-08 14:41 UTC, WilamisAviz15 commented on src/app/pages/contracts/contract-item/management-tab/management-tab.component.ts
> +          .map((message) => {
Eita, realmente faltou. Corrigido

2022-04-08 23:43 UTC, augustoicaro approved these changes

2022-04-09 04:57 UTC, merged

2022-04-09 05:00 UTC, augustoicaro commented
@WilamisAviz15 , mesmo problema do @Elygledson . Fez git push -f sem observar se todos os commits estavam lá e perdeu os commits que tu já havia passado para o branch. Vou resolver aqui, mas precisa ter mais atenção nas próximas vezes