Create routes for notifications
nortan-ninc/plataforma pull request #126
Opened 2022-04-06 01:01 UTC by EduhFarias

2022-04-06 16:56 UTC, WilamisAviz15 approved these changes

2022-04-06 23:28 UTC, augustoicaro requested changes
Dá uma olhada nos pontos que levantei.

2022-04-06 23:28 UTC, augustoicaro commented on backend/src/models/user.ts
> +  date: Date = new Date();
Trocar por `created` para normalizar os nomes que usam data e simplificar nos revivals

2022-04-06 23:28 UTC, augustoicaro commented on backend/src/routes/notification.ts
> +  updateNotification(req.body.notification, res);
Desse jeito você não garante que o `lastNotification` será o mesmo no decorrer da função. Se você receber 2 requisições ao mesmo tempo essa lógica já não faz sentido.

Deveriamo aplicar o mutex aqui para garantir que o `lastNotification` seja sempre o mesmo durante a execução, ou fazer ele ser parâmetro da função e deixar do mesmo jeito a estrutura.

2022-04-08 23:34 UTC, augustoicaro approved these changes

2022-04-08 23:35 UTC, merged