Limit comment of contract by author or team member
nortan-ninc/plataforma pull request #128
Opened 2022-04-07 00:24 UTC by WilamisAviz15

2022-04-07 18:10 UTC, leo-holanda requested changes
Levantei alguns pontos

2022-04-07 18:10 UTC, leo-holanda commented on src/app/pages/contracts/contract-item/management-tab/management-tab.component.ts
> +    });
Será que aqui não daria pra usar o this.invoice que foi atribuído na linha 92 se passar aquele trecho pro começo do ngOnInit? Como todo contract sempre tem um invoice aí acho que não seria problema, e evitaria duplicar esse trecho

2022-04-07 18:18 UTC, WilamisAviz15 commented on src/app/shared/services/message.service.spec.ts
> +            req.flush({ contract: tmpMessage });
é contract mesmo.

2022-04-07 18:28 UTC, WilamisAviz15 commented on src/app/shared/services/message.service.spec.ts
> +              }) as Message[]
Ah sim. Eu fiz esse commit em cima de outro, pois precisava do que tinha feito para outra task. O Augusto no commit anterior pediu para utilizar a reviveDates ja ajustei lá.

2022-04-07 18:29 UTC, WilamisAviz15 commented on src/app/pages/contracts/contract-item/management-tab/management-tab.component.ts
> +  responsibleSearch = '';
Fiz esse commit em cima de outro, pois precisava do que tinha feito para outra task. Removi nos ajustes do outro commit essa parte

2022-04-07 18:52 UTC, WilamisAviz15 commented on src/app/pages/contracts/contract-item/management-tab/management-tab.component.ts
> +    });
verdade. Feito!

2022-04-07 20:08 UTC, leo-holanda approved these changes
Massa! :+1:

2022-04-07 23:27 UTC, augustoicaro commented on src/app/shared/services/message.service.spec.ts
> +            req.flush({ contract: tmpMessage });
O @leo-holanda está certo. O retorno da rota de criação é:

``` js
return res.status(201).json({
    message: 'Comentário cadastrado!',
});
```

Logo se você está interceptando essa requisição, o retorno esperado é `{ message: "texo"}` ou `{ message: "texo", error: err}`

2022-04-07 23:36 UTC, augustoicaro requested changes
Vê os comentarios que fiz. Aproveita e faz um rebase depois para o branch `nws-1253`, lembra que toda vez que fizer um branch em cima de outro branch o PR tem que ser para o branch base

2022-04-07 23:36 UTC, augustoicaro commented on src/app/pages/contracts/contract-item/management-tab/management-tab.component.ts
> +      }
Aqui você poderia ter usado o `idToProperty` para pegar o time, aí nem ia precisar desse `if`. Seria bom reescrever essa parte só para exercitar

2022-04-08 14:50 UTC, WilamisAviz15 commented on src/app/shared/services/message.service.spec.ts
> +            req.flush({ contract: tmpMessage });
Ahhh. Entendi agora. Leo comentou da linha 101. Me confudi, eu tava olhando no print da imagem. Fiz a correção na branch nws-1253.

2022-04-08 23:36 UTC, WilamisAviz15 commented on src/app/pages/contracts/contract-item/management-tab/management-tab.component.ts
> +      }
feito

2022-04-09 00:15 UTC, augustoicaro approved these changes

2022-04-09 00:15 UTC, merged