Current user comments shown on the right
nortan-ninc/plataforma pull request #130
Opened 2022-04-07 19:12 UTC by WilamisAviz15

2022-04-07 23:47 UTC, augustoicaro requested changes

2022-04-07 23:47 UTC, augustoicaro commented on src/app/pages/contracts/contract-item/management-tab/management-tab.component.html
> +      [ngClass]="{ 'comment-current-user': userService.isEqual(comment.author, currentUser) }"
Usar `transformPipe` em conjução da função já utilizada

2022-04-07 23:47 UTC, augustoicaro commented on src/app/pages/contracts/contract-item/management-tab/management-tab.component.scss
> +    flex-direction: row-reverse;
Genial! Tu viu isso no curso, ou tu achou pesquisando como fazer?

2022-04-08 00:47 UTC, EduhFarias approved these changes

2022-04-08 14:09 UTC, WilamisAviz15 commented on src/app/pages/contracts/contract-item/management-tab/management-tab.component.scss
> +    flex-direction: row-reverse;
vi no curso que fiz de css

2022-04-08 23:55 UTC, augustoicaro approved these changes

2022-04-09 00:41 UTC, merged