Display popover/dropdown menu when clicking bell, displaying message list
nortan-ninc/plataforma pull request #133
Opened 2022-04-08 00:31 UTC by Elygledson

2022-04-08 18:18 UTC, leo-holanda requested changes
Levantei um ponto sobre uma propriedade do objeto de notificação. Ficou faltando só o screenshot com a imagem das notificações mas consegui abrir no GitPod e ver. Fiquei pensando se remover aquela margem abaixo do item da notificação cairia bem mas do jeito que tá funciona bem

2022-04-08 18:18 UTC, leo-holanda commented on src/app/@theme/components/header/header.component.html
> +              <span style="float: right">{{ notification.Date }}</span>
Normalmente as propriedades de um objeto começam com letra minúscula. Acho que valeria a pena fazer essa alteração no model

2022-04-08 18:18 UTC, leo-holanda commented on src/app/@theme/components/header/header.component.html
> +            ></nb-user>
Curioso que aqui o idToProperty funciona sem precisar do .bind(), mas lembro que em outros cantos já chegou a bugar quando não passava. Como tá funcionando, acho que pode deixar sem, mas achei curioso isso

2022-04-08 18:24 UTC, leo-holanda requested changes

2022-04-08 23:37 UTC, augustoicaro approved these changes

2022-04-08 23:37 UTC, augustoicaro commented on src/app/@theme/components/header/header.component.ts
> +    public userService: UserService,
concordo

2022-04-09 00:37 UTC, leo-holanda approved these changes

2022-04-09 00:44 UTC, merged