Create notification service
nortan-ninc/plataforma pull request #138
Opened 2022-04-13 02:56 UTC by EduhFarias

2022-04-13 18:18 UTC, leo-holanda requested changes
Alguns pontos que são mais dúvidas mesmo e algumas coisas pequenas.

2022-04-13 18:18 UTC, leo-holanda commented on src/app/shared/services/notification.service.spec.ts
> +              },
Eu notei que onde o _id é 1, o notifications é notifications.1, aí no caso do _id ser 0, o notifications precisaria ser notifications.0 também? Porque a ideia parece ser pra atualizar a lista de notificações do usuário de id 0 e 1

2022-04-13 18:18 UTC, leo-holanda commented on src/app/shared/services/notification.service.spec.ts
> +    userService.currentUser$.pipe(take(1)).subscribe();
Eu estranhei o currentUser$ aqui mas não sendo usado em outro lugar do teste. É alguma situação específica dos casos de teste?

2022-04-13 18:18 UTC, leo-holanda commented on src/app/shared/services/notification.service.spec.ts
> +    userService.getUsers().pipe(take(1)).subscribe();
Eu notei que essa função é chamada aqui e interceptada embaixo, mas lá nos casos de teste ela é chamada mas não é interceptada. É alguma situação específica dos testes também?

2022-04-13 20:25 UTC, EduhFarias commented on src/app/shared/services/notification.service.spec.ts
> +              },
O _id é referente ao documento que vai ser atualizado na coleção de usuários, já o .1 do notifications é indicando que será  inserido um objeto no array de notificações desse usuário e que ele será o primeiro objeto desse array, já que inicialmente ele é vazio.

2022-04-13 20:32 UTC, EduhFarias commented on src/app/shared/services/notification.service.spec.ts
> +    userService.currentUser$.pipe(take(1)).subscribe();
Bem notado, havia colocado pensando se fazer necessário a inicialização do usuário, mas o `authServiceSpy` já faz isso.

2022-04-13 20:40 UTC, EduhFarias commented on src/app/shared/services/notification.service.spec.ts
> +    mockedUsers.push(cloneDeep(tmpUser));
Verdade, vou fazer a remoção já que são propriedades não utilizadas nos testes.

2022-04-13 20:48 UTC, EduhFarias commented on src/app/shared/services/notification.service.spec.ts
> +    tmpTeamMember.sector = '1';
Isso, é um caso de teste, já que o objeto `UserNotification` tem o `.to` como `Ref<User>`.

2022-04-13 20:48 UTC, EduhFarias commented on src/app/shared/services/notification.service.spec.ts
> +    tmpInvoiceMember.sector = '1';
Isso, é um caso de teste, já que o objeto `UserNotification` tem o `.to` como `Ref<User>`.

2022-04-13 21:02 UTC, EduhFarias commented on src/app/shared/services/notification.service.spec.ts
> +    userService.getUsers().pipe(take(1)).subscribe();
Nesse caso, o mockedUsers está sendo adicionado no socket para que no caso de teste seja possível recuperar os usuários atualizados.

2022-04-13 22:35 UTC, leo-holanda commented on src/app/shared/services/notification.service.spec.ts
> +    userService.currentUser$.pipe(take(1)).subscribe();
:thumbsup:

2022-04-13 22:36 UTC, leo-holanda commented on src/app/shared/services/notification.service.spec.ts
> +    tmpInvoiceMember.sector = '1';
:thumbsup:

2022-04-13 22:36 UTC, leo-holanda commented on src/app/shared/services/notification.service.spec.ts
> +    mockedUsers.push(cloneDeep(tmpUser));
:thumbsup:

2022-04-13 22:36 UTC, leo-holanda commented on src/app/shared/services/notification.service.spec.ts
> +    tmpTeamMember.sector = '1';
Ahh massa!

2022-04-13 22:37 UTC, leo-holanda commented on src/app/shared/services/notification.service.spec.ts
> +              },
Ahh massa! Não sabia dessa!

2022-04-13 22:37 UTC, leo-holanda commented on src/app/shared/services/notification.service.spec.ts
> +    userService.getUsers().pipe(take(1)).subscribe();
:thumbsup:

2022-04-13 22:37 UTC, leo-holanda approved these changes

2022-04-14 22:27 UTC, augustoicaro commented on src/app/shared/services/notification.service.spec.ts
> +    userService.getUsers().pipe(take(1)).subscribe();
Essa é um ponto importante de deiar claro Leo. Quando fazemos uma requisição e interceptamos ela no `beforeEach` já tratamos o request que vai ser feito e a partir desse ponto vamos usar o cache do serviço. Por isso que não é preciso interceptar nos outros usos. É com o cache que diminuímos o número de requisições.

2022-04-14 23:42 UTC, augustoicaro requested changes
Faltou fazer os 2 outros casos de teste para o `notifyMany`

2022-04-16 01:36 UTC, augustoicaro approved these changes
Me faz por favor o rebase pro `main`. Depois faz um `rebase -i` e junta todos os commits do branch selecionando marcado cada um na opção ao lado como `squash`, ou o nome equivalente em português.

2022-04-19 22:51 UTC, merged