Change invoice complementary tab to match config
nortan-ninc/plataforma pull request #142
Opened 2022-04-15 18:44 UTC by EduhFarias

![Captura de tela de 2022-04-15 15-24-33](https://user-images.githubusercontent.com/30202709/163608827-854306a5-725a-4e26-b820-8a53eb2f3681.png)
Exemplo da aba complementar quando desativado todas as opções das configurações.
Lembrando que esse branch foi feito com base no branch NWS-1326 e possui algumas correções.

2022-04-16 02:13 UTC, augustoicaro approved these changes

2022-04-16 02:20 UTC, augustoicaro commented on src/app/pages/invoices/invoice-item/invoice-item.component.ts
> +      .pipe(take(1))
Aqui precisa ser o `takeUntil(this.destroy$)`, pois podemos abrir a configurações da plataforma em qualquer tela por ela ser um dialogo, logo temos que reagir a isso também.

2022-04-16 02:20 UTC, augustoicaro requested changes
Dá uma olhada nesse ponto que comentei

2022-04-16 18:01 UTC, EduhFarias commented on src/app/pages/invoices/invoice-item/invoice-item.component.ts
> +      .pipe(take(1))
Feito!

2022-04-18 13:24 UTC, leo-holanda requested changes
Só um detalhe bem pequeno mesmo

2022-04-18 13:24 UTC, leo-holanda commented on src/app/pages/invoices/invoice-item/invoice-item.component.ts
> +    private configService: ConfigService
Um detalhe bem pequeno mas acho que seria uma boa ordenar os parâmetros do construtor de acordo com o modificador de público ou privado, tipo primeiro os privados e depois os públicos, pra manter a consistência com outras partes do código

2022-04-18 13:27 UTC, leo-holanda requested changes
Requisitei revisão de mim mesmo sem querer :zany_face:

2022-04-18 23:47 UTC, EduhFarias commented on src/app/pages/invoices/invoice-item/invoice-item.component.ts
> +    private configService: ConfigService
Massa, feito!

2022-04-19 22:41 UTC, leo-holanda approved these changes

2022-04-20 19:39 UTC, augustoicaro commented on src/app/pages/invoices/invoice-item/invoice-item.component.ts
> +      .pipe(take(1))
Na verdade não precisava, foi vacilo meu. Não conseguimos abrir as configuraçõe com um outro dialogo aberto. Não me dei conta que estávamos no `invoice-item`, desfaz esse commit por favor

2022-04-20 19:41 UTC, augustoicaro approved these changes
Remove aquele commit que comentei e aproveita e junto tudo de novo nesse branch a partir do commit que você começa a fazer as alterações dessa tarefa

2022-04-20 19:46 UTC, augustoicaro commented
Faltou alterar a base desse PR para o branch `nws-1326`

2022-04-20 23:57 UTC, merged