Change pdf service to match platform invoiceConfig
nortan-ninc/plataforma pull request #143
Opened 2022-04-15 19:36 UTC by EduhFarias

[ORC---969_2022-NRT_DAD.pdf](https://github.com/nortan-ninc/plataforma/files/8497931/ORC---969_2022-NRT_DAD.pdf)
Exemplo com todas as configurações desativadas para o orçamento ORC---969_2022-NRT_DAD.
Lembrando que este branch foi feito com base no branch NWS-1327, que possui alterações importantes em relação ao NWS-1326.

2022-04-16 02:31 UTC, augustoicaro requested changes
Mesma coisa do passado e um ponto a mais sobre o tratamento do cabeçalho

2022-04-16 02:31 UTC, augustoicaro commented on src/app/pages/invoices/pdf.service.ts
> +      .pipe(take(1))
Aqui precisa ser o `takeUntil(this.destroy$)`, pois podemos abrir a configurações da plataforma em qualquer tela por ela ser um dialogo, logo temos que reagir a isso também.

2022-04-16 02:31 UTC, augustoicaro commented on src/app/pages/invoices/pdf.service.ts
> +        ],
Em vez de fazer esse `if` e `else` prepara a colunas por fora numa lista inicializando com a logo e se o header tiver ativo você dá um push na lista desse segundo objeto de texto

2022-04-16 18:13 UTC, EduhFarias commented on src/app/pages/invoices/pdf.service.ts
> +      .pipe(take(1))
Feito!

2022-04-16 18:13 UTC, EduhFarias commented on src/app/pages/invoices/pdf.service.ts
> +        ],
Feito!

2022-04-18 11:51 UTC, Elygledson commented on src/app/@theme/components/header/config/config.component.html
> +              <td class="td-left">Importantes:</td>
Eu estava pensando se é realmente necessário os dois pontos antes das toggles mas se caso for algum pedido desconsidere o comentário.

2022-04-18 11:55 UTC, Elygledson approved these changes

2022-04-18 23:00 UTC, EduhFarias commented on src/app/@theme/components/header/config/config.component.html
> +              <td class="td-left">Importantes:</td>
Opa Elygledson, bem notado. Fiz a mudança no branch NWS-1326, onde é criado a tabela de configuração.

2022-04-20 19:45 UTC, augustoicaro approved these changes

2022-04-20 19:45 UTC, augustoicaro commented on src/app/pages/invoices/pdf.service.ts
> +      });
Foi mal, vacilo meu novamente, aui não faz sentido também fazer assim. Volta o commit passado, desfaz essa alteração e refaz o commit por favor.

2022-04-20 19:46 UTC, augustoicaro commented
Faltou alterar a base desse PR para o branch `nws-1326`

2022-04-21 23:40 UTC, merged