[NWS-1321][NWS-1324] Change logo on login page
nortan-ninc/plataforma pull request #149
Opened 2022-04-20 23:10 UTC by EduhFarias

![login](https://user-images.githubusercontent.com/30202709/164339374-fdda121b-9499-4751-9ebc-e83e8205e989.png)

2022-04-25 23:37 UTC, augustoicaro requested changes
Se continuar png, deixa a altura como 512. O melhor cenário seria trocar o png por svg.

2022-04-26 02:27 UTC, EduhFarias commented
![Captura de tela de 2022-04-25 23-25-03](https://user-images.githubusercontent.com/30202709/165207402-e2af7a9b-4a7f-492c-8d1d-582f1ee4bb9b.png)
Visualização da alteração de png por svg.

2022-04-26 22:36 UTC, augustoicaro approved these changes

2022-04-26 23:46 UTC, augustoicaro commented
@WilamisAviz15 , não esquece de revisar esse também

2022-04-27 23:25 UTC, WilamisAviz15 approved these changes

2022-04-28 00:21 UTC, merged