[NWS-1172][NWS-1347] Fix notification badge and getTime()
nortan-ninc/plataforma pull request #150
Opened 2022-04-21 03:56 UTC by Elygledson

2022-04-21 23:48 UTC, augustoicaro approved these changes

2022-04-21 23:56 UTC, leo-holanda requested changes

2022-04-21 23:56 UTC, leo-holanda commented on src/app/shared/services/utils.service.ts
> +  reviveDates<T>(users: T): T {
Acho que seria uma boa um nome mais genérico pra esse parâmetro, pois ele pode ser usado em outros objetos que não users, tipo promotions.

2022-04-22 00:08 UTC, leo-holanda requested changes

2022-04-22 00:08 UTC, leo-holanda commented on src/app/shared/services/utils.service.ts
> +      return v;
Sei que já tava assim antes, mas acho que seria uma boa também trocar k e v por key e value. Mesmo sendo algo pequeno, acho que evitar usar letras como nome de variável é sempre bom.

2022-04-22 00:22 UTC, augustoicaro commented on src/app/shared/services/utils.service.ts
> +  reviveDates<T>(users: T): T {
Concordo, poder ser `Obj`

2022-04-22 00:22 UTC, augustoicaro commented on src/app/shared/services/utils.service.ts
> +      return v;
Concordo. Já estava assim, mas é sempre bom melhorar

2022-04-22 01:33 UTC, Elygledson commented on src/app/shared/services/utils.service.ts
> +  reviveDates<T>(users: T): T {
feito.

2022-04-25 22:43 UTC, leo-holanda requested changes

2022-04-25 22:43 UTC, leo-holanda commented on src/app/shared/services/utils.service.ts
> +  reviveDates<T>(Obj: T): T {
Um detalhe bem pequeno que é o nome do parâmetro. Normalmente a letra inicial é minúscula

2022-04-25 22:49 UTC, Elygledson commented on src/app/shared/services/utils.service.ts
> +  reviveDates<T>(Obj: T): T {
Feito.

2022-04-25 23:02 UTC, leo-holanda approved these changes

2022-04-25 23:42 UTC, augustoicaro approved these changes

2022-04-25 23:42 UTC, merged