[NWS-1207][NWS-1318] Separate contract items receipt tab for individual component
nortan-ninc/plataforma pull request #154
Opened 2022-04-22 01:18 UTC by WilamisAviz15

2022-04-26 00:03 UTC, leo-holanda requested changes

2022-04-26 00:03 UTC, leo-holanda commented on src/app/pages/contracts/contract-item/receipt-tab/receipt-tab.component.ts
> +  @Output() response = new EventEmitter<void>();
Pelo que vi o response é um eventEmitter que é emitido cada vez que os receipts mudam através dos diálogos. Seria uma boa trocar o nome de response pra tipo receiptsChanged ou algo assim?

2022-04-26 00:34 UTC, WilamisAviz15 commented on src/app/pages/contracts/contract-item/receipt-tab/receipt-tab.component.ts
> +  @Output() response = new EventEmitter<void>();
feito

2022-04-26 00:37 UTC, WilamisAviz15 commented on src/app/pages/contracts/contract-item/balance-tab/balance-tab.component.ts
> +  teamMember: any = {};
Eita. Acabei esquecendo de tirar. Essa variável é usada na aba de dados.

2022-04-26 00:42 UTC, WilamisAviz15 commented on src/app/pages/contracts/contract-item/receipt-tab/receipt-tab.component.ts
> +  @Input() contract: Contract = new Contract();
feito

2022-04-28 00:17 UTC, augustoicaro requested changes

2022-04-28 00:23 UTC, WilamisAviz15 commented on src/app/pages/contracts/contract-item/contract-item.component.ts
> +  sendResponseEmmiter() {
feito

2022-04-28 00:53 UTC, leo-holanda requested changes

2022-04-28 00:53 UTC, leo-holanda commented on src/app/pages/contracts/contract-item/contract-item.component.ts
>    }
Eita @WilamisAviz15 foi mal :slightly_frowning_face: esqueci de marcar esse cara também. Tu acha que faria sentido trocar ele também pra receiptsChanged ou algo assim?

2022-04-28 00:53 UTC, leo-holanda commented on src/app/pages/contracts/contract-item/contract-item.component.html
> +      (response)="responseEmitter()"
Mesma coisa do outro comentário

2022-04-29 00:11 UTC, WilamisAviz15 commented on src/app/pages/contracts/contract-item/contract-item.component.ts
>    }
Augusto sugeriu forwardResponse

2022-04-29 00:15 UTC, augustoicaro approved these changes

2022-04-29 00:16 UTC, leo-holanda approved these changes

2022-04-29 00:41 UTC, merged