[NWS-1172][NWS-1371] Always refresh notification box when removing or…
nortan-ninc/plataforma pull request #162
Opened 2022-04-27 00:23 UTC by Elygledson

… receiving new notifications

2022-04-27 18:26 UTC, leo-holanda requested changes

2022-04-27 18:26 UTC, leo-holanda commented on src/app/@theme/components/header/header.component.ts
> +        if (matchedUser) this.user = matchedUser;
Pelo que entendi, a variável user guarda o usuário corrente do tipo User que é atribuído na linha 67. Nas linhas 80-81, a lista de usuários é varrida buscando o usuário com id igual ao do usuário corrente (this.user) e, se ele existir, é atribuído à variável user. Como os dois são feitos separadamente, não sei qual aconteceria primeiro. Será que dá pra garantir que o this.user vai tá preenchido antes da comparação da linha 80 acontecer? É mais uma dúvida técnica mesmo que não tive certeza

Fiquei na dúvida qual seria o caso de uso da getUsers nesse cenário, porque o usuário corrente já seria atribuído de qualquer forma na linha 67. Seria pra carregar a lista de usuários?

2022-04-27 23:05 UTC, leo-holanda approved these changes

2022-04-29 23:10 UTC, augustoicaro approved these changes

2022-04-29 23:11 UTC, merged