[NWS-1321][NWS-1329] Change background image(layout of each page) pdf
nortan-ninc/plataforma pull request #164
Opened 2022-04-27 01:45 UTC by Elygledson

…invoice pdf

2022-04-28 23:28 UTC, WilamisAviz15 requested changes

2022-04-28 23:28 UTC, WilamisAviz15 commented on src/app/pages/invoices/pdf.service.ts
>        pageBreak: invoice.team ? (invoice.team.length == 3 || invoice.team.length == 4 ? 'before' : 'none') : 'none',
Faltou trocar na linha 553 a cor para #FF8800

2022-04-29 02:11 UTC, Elygledson commented on src/app/pages/invoices/pdf.service.ts
>        pageBreak: invoice.team ? (invoice.team.length == 3 || invoice.team.length == 4 ? 'before' : 'none') : 'none',
Feito.

2022-05-03 00:35 UTC, WilamisAviz15 approved these changes

2022-05-03 22:58 UTC, augustoicaro approved these changes

2022-05-03 23:00 UTC, merged