[NWS-1172][NWS-1269] Create dialog to open notification and delete on dismiss
nortan-ninc/plataforma pull request #165
Opened 2022-04-27 03:12 UTC by EduhFarias

![Captura de tela de 2022-04-27 00-00-40](https://user-images.githubusercontent.com/30202709/165432336-22eccc4f-40fb-48c3-b756-7033d699dcb8.png)
Dialogo da notificação selecionada.

2022-04-27 23:51 UTC, leo-holanda requested changes

2022-04-27 23:51 UTC, leo-holanda commented on src/app/@theme/components/header/config/config-dialog/config-dialog.component.ts
> +  @Input() notificationIndex?: number;
Será que a gente podia assumir também que o notificationIndex não seria opcional? Eu pensei nisso porque o cara só poderia abrir o diálogo se houvesse uma notificação pra clicar, aí se houvesse notificação sempre haveria index que viria pelo ngFor

2022-04-27 23:51 UTC, leo-holanda commented on src/app/shared/services/notification.service.ts
> +      if (newNotification.to) newNotification.to = this.userService.idToUser(newNotification.to);
Como nesse caso o newNotification.to estaria preenchido no if/else anterior, será que poderia omitir esse último if?

2022-04-27 23:51 UTC, leo-holanda commented on backend/src/routes/notification.ts
> +        if (isEqual(req.body.notification, lastNotification)) {
Fiquei em dúvida do por que que essa checagem acontece :thinking: no caso seria pra verificar se a notificação a ser apagada é a última cadastrada?

2022-04-27 23:51 UTC, leo-holanda commented on src/app/shared/services/notification.service.spec.ts
> +            }) as UserNotification[];
Acho que seria uma boa usar o reviveDates do utils nesse trecho

2022-04-28 00:20 UTC, EduhFarias commented on backend/src/routes/notification.ts
> +        if (isEqual(req.body.notification, lastNotification)) {
Vacilo meu, acabei esquecendo de apagar quando reaproveitei a função.

2022-04-28 01:00 UTC, EduhFarias commented on src/app/@theme/components/header/config/config-dialog/config-dialog.component.ts
> +  @Input() notificationIndex?: number;
Poderíamos se fosse atribuído algum valor inicial, o que eu acho que não se faz necessário porque esse dialogo também é utilizado pelas configurações. Daí quando é chamado a configuração da plataforma essa propriedade não é passada no contexto do dialogo. Mas vale o debate, o que você acha @augustoicaro ?

2022-04-28 01:04 UTC, EduhFarias commented on src/app/@theme/components/header/header.component.ts
> +        title: event.data?.title,
Sim, faz sentido. Eu havia optado por fazer assim para seguir o padrão dos outros dialogos, mas como não há outro tipo de dado que possa ser passado eu farei a mudança!

2022-04-28 01:05 UTC, EduhFarias commented on src/app/shared/services/notification.service.spec.ts
> +            }) as UserNotification[];
Feito!

2022-04-28 01:10 UTC, EduhFarias commented on src/app/shared/services/notification.service.ts
> +      if (newNotification.to) newNotification.to = this.userService.idToUser(newNotification.to);
Como o newNotification.to é do tipo Ref<User> ele pode ser undefined, então é preciso fazer a verificação.

2022-04-28 22:36 UTC, leo-holanda commented on src/app/shared/services/notification.service.ts
> +      if (newNotification.to) newNotification.to = this.userService.idToUser(newNotification.to);
Ahhh massa! Não pensei nisso

2022-04-28 22:39 UTC, leo-holanda commented on src/app/@theme/components/header/config/config-dialog/config-dialog.component.ts
> +  @Input() notificationIndex?: number;
Ahh é verdade Eduardo, não pensei nisso também

2022-04-29 22:21 UTC, leo-holanda approved these changes

2022-05-03 23:09 UTC, augustoicaro approved these changes

2022-05-03 23:09 UTC, augustoicaro commented on src/app/@theme/components/header/config/config-dialog/config-dialog.component.ts
> +  @Input() notificationIndex?: number;
Concordo com o que você argumentou Eduardo

2022-05-03 23:10 UTC, merged